version: 2
jobs:
 qgis_docker:
   machine: true
   steps:
     - checkout
     - run:
           name: "Build qgis_docker Container"
           command: |
            docker build -f Dockerfile -t qgis_docker .
     - deploy:
           name: "Push to Docker Hub"
           command: |
              if [ "${CIRCLE_BRANCH}" == "master" ]; then
                docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASS
                docker push cmzambranat/qgis
              fi
workflows:
   version: 2
   commit:
     jobs:
       - qgis_docker
